services:
  mongodb:
    build: ./mongodb
    image: mongodb:v1
    container_name: mongodb

  catalogue:
    build: ./catalogue
    image: catalogue:v1
    container_name: catalogue
    depends_on: 
      - mongodb 
  frontend:
    build: ./frontend
    image: frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on: 
      - catalogue
      - user

  redis:
    image: redis 
    container_name: redis 

  user:
    build: ./user
    image: user:v1
    container_name: user
    depends_on: 
      - redis
      - mongodb 

  cart:
    build: ./cart
    image: cart:v1
    container_name: cart
    depends_on: 
      - redis
      - catalogue
      
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually